spring:
  application:
    name:
      Recorder
logging:
  level:
    root: info
    site.nimou.recorder: debug
recorder:
  detector:
    sample-rate: 44100
    threshold-dB: 20
    buffer-size: 2048
    db-queue-size: 20
  record-time: 10
  record-file-path: D:\MYR
