spring:
  application:
    name:
      Recorder
logging:
  level:
    root: info
    site.nimou.recorder: debug
  charset:
    file: utf-8
    console: utf-8
  file:
    name: ./logs/recorderLog.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
recorder:
  detector:
    sample-rate: 44100
    threshold-dB: 15
    buffer-size: 2048
    db-queue-size: 20
  record-time: 10
  record-file-path: D:\MYR
file:
  minio:
    accessKey: 5LgBpCWx4NutbR1MJDCa
    secretKey: rmpgQx3oabcVUgvcG61DUXNxx92XKFgauFTodtid